const nodemailer = require('nodemailer');
const config = require('../config');

const transporter = nodemailer.createTransport({
    host: config.smtp.host,
    port: config.smtp.port,
    secure: config.smtp.port === 465, // true for 465, false for other ports
    auth: {
        user: config.smtp.user,
        pass: config.smtp.pass
    }
});

async function sendDailyBrief(items) {
    if (!items || items.length === 0) {
        console.log('No items to send.');
        return;
    }

    const date = new Date().toLocaleDateString('zh-CN');
    const time = new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });

    let htmlContent = `
    <html>
    <head>
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: #b92b27; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
            .card { background: #f9f9f9; border-left: 4px solid #b92b27; margin-bottom: 20px; padding: 15px; border-radius: 4px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .tag { display: inline-block; padding: 2px 8px; background: #e0e0e0; font-size: 12px; border-radius: 10px; margin-right: 5px; color: #555; }
            .golden { color: #b92b27; font-weight: bold; font-style: italic; margin-top: 10px; display: block; }
            .history { color: #555; font-size: 0.9em; margin-top: 5px; }
            .footer { text-align: center; font-size: 12px; color: #999; margin-top: 30px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>每日选题情报</h1>
                <p>${date} ${time} | 核心筛选: ${items.length}条</p>
            </div>
            
            ${items.map((item, index) => `
            <div class="card">
                <h3><a href="${item.link}" target="_blank" style="text-decoration:none; color:#333;">#${index + 1} ${item.title}</a></h3>
                <div style="margin-bottom:8px;">
                    <span class="tag">${item.source}</span>
                </div>
                <p style="color:#666; font-size:14px;">${item.summary}</p>
                <div style="margin-top:10px;">
                    <a href="${item.link}" style="color:#b92b27; font-weight:bold; font-size:12px;">🔗 点击阅读原文</a>
                </div>
            </div>
            `).join('')}

            <div class="footer">
                <p>Generated by Daily Insight Radar</p>
            </div>
        </div>
    </body>
    </html>
    `;

    try {
        const info = await transporter.sendMail({
            from: `"Insight Radar" <${config.smtp.user}>`,
            to: config.smtp.to,
            subject: `【选题雷达】${date} ${time} 汇报 (${items.length}条)`,
            html: htmlContent
        });
        console.log('Email sent: %s', info.messageId);
    } catch (error) {
        console.error('Error sending email:', error);
    }
}

module.exports = { sendDailyBrief };
